# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160824_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_a',
        ),
    ]
