# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20160824_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
